In [4]:
import torch
import torch.optim as optim
torch.manual_seed(1)

#데이터 가져오기
import numpy as np 
import pandas as pd

train_data=pd.read_csv('train.csv')
train_data

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0          5    0    0    0    0    0    0    0    0    0  ...      0      0   
1          0    0    0    0    0    0    0    0    0    0  ...      0      0   
2          3    0    0    0    0    0    0    0    0    0  ...      0      0   
3          3    0    0    0    0    0    0    0    0    0  ...      0      0   
4          6    0    0    0    0    0    0    0    0    0  ...      0      0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
59995      0    0    0    0    0    0    0    0    0    0  ...      0      0   
59996      3    0    0    0    0    0    0    0    0    0  ...      0      0   
59997      9    0    0    0    0    0    0    0    0    0  ...      0      0   
59998      4    0    0    0    0    0    0    0    0    0  ...      0      0   
59999      6    0    0    0    0    0    0    0    0    0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
59995      0      0      0      0      0      0      0      0  
59996      0      0      0      0      0      0      0      0  
59997      0      0      0      0      0      0      0      0  
59998      0      0      0      0      0      0      0      0  
59999      0      0      0      0      0      0      0      0  

[60000 rows x 785 columns]

In [5]:
x_train=train_data.copy()
x_train=x_train.drop('label',axis=1)
x_train = torch.FloatTensor(x_train.values)


y_train=train_data['label'].copy()
y_train = torch.LongTensor(y_train.values)

print(x_train)
print(y_train)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([5, 0, 3,  ..., 9, 4, 6])


In [6]:
import torch.nn.functional as F

nb_class = 10
nb_data = len(y_train)

W = torch.zeros((28*28, nb_class), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=0.00001)
nb_epochs = 10000

for epoch in range(nb_epochs + 1):

    hypothesis = F.softmax(x_train.matmul(W) + b, dim=1)
    
    cost = F.cross_entropy((x_train.matmul(W) + b), y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/10000 Cost: 2.302585
Epoch  100/10000 Cost: 0.377047
Epoch  200/10000 Cost: 0.338156
Epoch  300/10000 Cost: 0.320888
Epoch  400/10000 Cost: 0.310511
Epoch  500/10000 Cost: 0.303357
Epoch  600/10000 Cost: 0.298011
Epoch  700/10000 Cost: 0.293798
Epoch  800/10000 Cost: 0.290351
Epoch  900/10000 Cost: 0.287450
Epoch 1000/10000 Cost: 0.284958
Epoch 1100/10000 Cost: 0.282781
Epoch 1200/10000 Cost: 0.280853
Epoch 1300/10000 Cost: 0.279127
Epoch 1400/10000 Cost: 0.277567
Epoch 1500/10000 Cost: 0.276147
Epoch 1600/10000 Cost: 0.274846
Epoch 1700/10000 Cost: 0.273645
Epoch 1800/10000 Cost: 0.272533
Epoch 1900/10000 Cost: 0.271498
Epoch 2000/10000 Cost: 0.270531
Epoch 2100/10000 Cost: 0.269624
Epoch 2200/10000 Cost: 0.268770
Epoch 2300/10000 Cost: 0.267965
Epoch 2400/10000 Cost: 0.267203
Epoch 2500/10000 Cost: 0.266481
Epoch 2600/10000 Cost: 0.265794
Epoch 2700/10000 Cost: 0.265141
Epoch 2800/10000 Cost: 0.264517
Epoch 2900/10000 Cost: 0.263921
Epoch 3000/10000 Cost: 0.263350
Epoch 31

In [7]:
# 학습된 W,b를 통한 클래스 예측
hypothesis = F.softmax(x_train.matmul(W) + b, dim=1)
predict = torch.argmax(hypothesis, dim=1)

print(hypothesis)
print(predict)
print(y_train)


# 정확도 계산 
correct_prediction = predict.float() == y_train
print(correct_prediction)
accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('The model has an accuracy of {:2.2f}% for the training set.'.format(accuracy * 100))



tensor([[1.4496e-06, 2.5391e-04, 7.0796e-05,  ..., 5.5544e-06, 1.5105e-01,
         8.7840e-06],
        [9.9660e-01, 7.7812e-12, 5.7747e-07,  ..., 1.4206e-09, 3.0747e-06,
         3.8571e-09],
        [1.1647e-05, 1.5339e-06, 4.3255e-04,  ..., 2.6909e-07, 2.1167e-03,
         1.2925e-04],
        ...,
        [7.4933e-10, 2.0217e-05, 5.4268e-06,  ..., 6.1277e-02, 4.9542e-03,
         9.2694e-01],
        [1.1719e-02, 1.6400e-08, 2.9101e-02,  ..., 8.3274e-06, 1.4079e-02,
         8.8939e-04],
        [1.3635e-04, 5.4580e-06, 9.0227e-04,  ..., 1.8366e-08, 8.5591e-03,
         1.2785e-04]], grad_fn=<SoftmaxBackward0>)
tensor([5, 0, 3,  ..., 9, 4, 6])
tensor([5, 0, 3,  ..., 9, 4, 6])
tensor([True, True, True,  ..., True, True, True])
The model has an accuracy of 93.36% for the training set.


In [8]:
#테스트 데이터 가져오기
test_data=pd.read_csv('test.csv')
test_data

1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  1x10  ...  28x19  28x20  \
0       0    0    0    0    0    0    0    0    0     0  ...      0      0   
1       0    0    0    0    0    0    0    0    0     0  ...      0      0   
2       0    0    0    0    0    0    0    0    0     0  ...      0      0   
3       0    0    0    0    0    0    0    0    0     0  ...      0      0   
4       0    0    0    0    0    0    0    0    0     0  ...      0      0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...    ...    ...   
9995    0    0    0    0    0    0    0    0    0     0  ...      0      0   
9996    0    0    0    0    0    0    0    0    0     0  ...      0      0   
9997    0    0    0    0    0    0    0    0    0     0  ...      0      0   
9998    0    0    0    0    0    0    0    0    0     0  ...      0      0   
9999    0    0    0    0    0    0    0    0    0     0  ...      0      0   

      28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0         0      0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...    ...  
9995      0      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0      0  
9999      0      0      0      0      0      0      0      0  

[10000 rows x 784 columns]

In [9]:
#정확도 측정
test_data = torch.FloatTensor(test_data.values)
hypothesis = F.softmax(test_data.matmul(W) + b, dim=1)
predict = torch.argmax(hypothesis, dim=1)

In [10]:
submit=pd.read_csv("sample_submit.csv")

for i, value in enumerate(predict):
    submit["label"][i]=value.item()

submit.label=submit.label.astype(int)

submit.to_csv("submit_1.csv",index=False)

C:\Users\bjw01\AppData\Local\Temp\ipykernel_14728\1510365401.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  submit["label"][i]=value.item()
