In [ ]:
import torch
import torch.optim as optim

torch.manual_seed(1)

In [ ]:
#데이터 가져오기
import numpy as np 
import pandas as pd

train_data=pd.read_csv('train.csv')
train_data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              1       95             60             18       58  23.9   
1              5      105             72             29      325  36.9   
2              0      135             68             42      250  42.3   
3              4      131             68             21      166  33.1   
4              1      103             30             38       83  43.3   
..           ...      ...            ...            ...      ...   ...   
532            5      139             64             35      140  28.6   
533            1       96            122              0        0  22.4   
534           10      101             86             37        0  45.6   
535            0      141              0              0        0  42.4   
536            0      125             96              0        0  22.5   

     DiabetesPedigreeFunction  Age  Diabetes  
0                       0.260   22         0  
1                       0.159   28         0  
2                       0.365   24         1  
3                       0.160   28         0  
4                       0.183   33         0  
..                        ...  ...       ...  
532                     0.411   26         0  
533                     0.207   27         0  
534                     1.136   38         1  
535                     0.205   29         1  
536                     0.262   21         0  

[537 rows x 9 columns]

In [ ]:
#데이터 가공
x_train=train_data.copy()
x_train=x_train.drop('Diabetes',axis=1)
x_train = torch.FloatTensor(x_train.values)


y_train=train_data['Diabetes'].copy()
y_train = torch.FloatTensor(y_train.values)
y_train=y_train.reshape(537,1)

print(x_train)
print(y_train)

tensor([[  1.0000,  95.0000,  60.0000,  ...,  23.9000,   0.2600,  22.0000],
        [  5.0000, 105.0000,  72.0000,  ...,  36.9000,   0.1590,  28.0000],
        [  0.0000, 135.0000,  68.0000,  ...,  42.3000,   0.3650,  24.0000],
        ...,
        [ 10.0000, 101.0000,  86.0000,  ...,  45.6000,   1.1360,  38.0000],
        [  0.0000, 141.0000,   0.0000,  ...,  42.4000,   0.2050,  29.0000],
        [  0.0000, 125.0000,  96.0000,  ...,  22.5000,   0.2620,  21.0000]])
tensor([[0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]

In [ ]:
# 모델 초기화
W = torch.zeros((8, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=1e-4)

nb_epochs = 1000000
for epoch in range(nb_epochs + 1):

    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    loss=torch.nn.BCELoss()
    cost=loss(hypothesis,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))


스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
Epoch 500100/1000000 Cost: 0.557726
Epoch 500200/1000000 Cost: 0.557717
Epoch 500300/1000000 Cost: 0.557708
Epoch 500400/1000000 Cost: 0.557699
Epoch 500500/1000000 Cost: 0.557690
Epoch 500600/1000000 Cost: 0.557681
Epoch 500700/1000000 Cost: 0.557672
Epoch 500800/1000000 Cost: 0.557663
Epoch 500900/1000000 Cost: 0.557654
Epoch 501000/1000000 Cost: 0.557645
Epoch 501100/1000000 Cost: 0.557636
Epoch 501200/1000000 Cost: 0.557627
Epoch 501300/1000000 Cost: 0.557618
Epoch 501400/1000000 Cost: 0.557609
Epoch 501500/1000000 Cost: 0.557600
Epoch 501600/1000000 Cost: 0.557591
Epoch 501700/1000000 Cost: 0.557582
Epoch 501800/1000000 Cost: 0.557574
Epoch 501900/1000000 Cost: 0.557565
Epoch 502000/1000000 Cost: 0.557556
Epoch 502100/1000000 Cost: 0.557547
Epoch 502200/1000000 Cost: 0.557538
Epoch 502300/1000000 Cost: 0.557529
Epoch 502400/1000000 Cost: 0.557520
Epoch 502500/1000000 Cost: 0.557511
Epoch 502600/1000000 Cost: 0.557502
Epoch 502700/1000000 Cost: 0

In [ ]:
#데이터 평가
hypothesis = torch.sigmoid(x_train.matmul(W) + b)

prediction = hypothesis >= torch.FloatTensor([0.5])

correct_prediction = prediction.float() == y_train
print(correct_prediction[:5])

accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('The model has an accuracy of {:2.2f}% for the training set.'.format(accuracy * 100))

tensor([[ True],
        [ True],
        [False],
        [ True],
        [False]])
The model has an accuracy of 74.49% for the training set.


In [ ]:
#테스트 데이터 가져오기
test_data=pd.read_csv('test.csv')
test_data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6       98             58             33      190  34.0   
1              2      112             75             32        0  35.7   
2              2      108             64              0        0  30.8   
3              8      107             80              0        0  24.6   
4              7      136             90              0        0  29.9   
..           ...      ...            ...            ...      ...   ...   
226            0      119              0              0        0  32.4   
227            4      109             64             44       99  34.8   
228            0      127             80             37      210  36.3   
229            6      105             70             32       68  30.8   
230            5       77             82             41       42  35.8   

     DiabetesPedigreeFunction  Age  
0                       0.430   43  
1                       0.148   21  
2                       0.158   21  
3                       0.856   34  
4                       0.210   50  
..                        ...  ...  
226                     0.141   24  
227                     0.905   26  
228                     0.804   23  
229                     0.122   37  
230                     0.156   35  

[231 rows x 8 columns]

In [ ]:
#정확도 측정
test_data = torch.FloatTensor(test_data.values)
hypothesis = torch.sigmoid(test_data.matmul(W) + b)
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)

tensor([[False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [False],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [False],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [ True],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [False],
        [False],
        [ True],
        [False],
        [ True],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [False],
        [ True],
        [ True],
        [False],
        [False],
        [False],
        [ True],
        [False],
        [False

In [ ]:
id=[]
diabetes=[]

for i in range(len(prediction)):
    id.append(i)
    diabetes.append(int(prediction[i].item()))

In [ ]:
submit = pd.DataFrame({'Id':id,
                       'Diabetes':diabetes})
submit.to_csv("submit.csv",index=None)