In [1]:
import torch
import torch.optim as optim

torch.manual_seed(1)

c:\Users\bjw01\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\random.py:42: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  return default_generator.manual_seed(seed)


In [17]:
#데이터 가져오기
import numpy as np 
import pandas as pd

train_data=pd.read_csv('train.csv')
train_data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              1       95             60             18       58  23.9   
1              5      105             72             29      325  36.9   
2              0      135             68             42      250  42.3   
3              4      131             68             21      166  33.1   
4              1      103             30             38       83  43.3   
..           ...      ...            ...            ...      ...   ...   
532            5      139             64             35      140  28.6   
533            1       96            122              0        0  22.4   
534           10      101             86             37        0  45.6   
535            0      141              0              0        0  42.4   
536            0      125             96              0        0  22.5   

     DiabetesPedigreeFunction  Age  Diabetes  
0                       0.260   22         0  
1                       0.159   28         0  
2                       0.365   24         1  
3                       0.160   28         0  
4                       0.183   33         0  
..                        ...  ...       ...  
532                     0.411   26         0  
533                     0.207   27         0  
534                     1.136   38         1  
535                     0.205   29         1  
536                     0.262   21         0  

[537 rows x 9 columns]

In [23]:
#데이터 가공
x_train=train_data.copy()
x_train=x_train.drop('Diabetes',axis=1)
x_train = torch.FloatTensor(x_train.values)


y_train=train_data['Diabetes'].copy()
y_train = torch.FloatTensor(y_train.values)
y_train=y_train.reshape(537,1)

print(x_train)
print(y_train)

tensor([[  1.0000,  95.0000,  60.0000,  ...,  23.9000,   0.2600,  22.0000],
        [  5.0000, 105.0000,  72.0000,  ...,  36.9000,   0.1590,  28.0000],
        [  0.0000, 135.0000,  68.0000,  ...,  42.3000,   0.3650,  24.0000],
        ...,
        [ 10.0000, 101.0000,  86.0000,  ...,  45.6000,   1.1360,  38.0000],
        [  0.0000, 141.0000,   0.0000,  ...,  42.4000,   0.2050,  29.0000],
        [  0.0000, 125.0000,  96.0000,  ...,  22.5000,   0.2620,  21.0000]])
tensor([[0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]

In [37]:
# 모델 초기화
W = torch.zeros((8, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=1e-4)

nb_epochs = 100000
for epoch in range(nb_epochs + 1):

    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    loss=torch.nn.BCELoss()
    cost=loss(hypothesis,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))


Epoch    0/100000 Cost: 0.693147
Epoch  100/100000 Cost: 0.632095
Epoch  200/100000 Cost: 0.626077
Epoch  300/100000 Cost: 0.624470
Epoch  400/100000 Cost: 0.623757
Epoch  500/100000 Cost: 0.623312
Epoch  600/100000 Cost: 0.622986
Epoch  700/100000 Cost: 0.622724
Epoch  800/100000 Cost: 0.622504
Epoch  900/100000 Cost: 0.622311
Epoch 1000/100000 Cost: 0.622137
Epoch 1100/100000 Cost: 0.621976
Epoch 1200/100000 Cost: 0.621825
Epoch 1300/100000 Cost: 0.621682
Epoch 1400/100000 Cost: 0.621545
Epoch 1500/100000 Cost: 0.621413
Epoch 1600/100000 Cost: 0.621287
Epoch 1700/100000 Cost: 0.621164
Epoch 1800/100000 Cost: 0.621045
Epoch 1900/100000 Cost: 0.620930
Epoch 2000/100000 Cost: 0.620818
Epoch 2100/100000 Cost: 0.620709
Epoch 2200/100000 Cost: 0.620603
Epoch 2300/100000 Cost: 0.620500
Epoch 2400/100000 Cost: 0.620400
Epoch 2500/100000 Cost: 0.620303
Epoch 2600/100000 Cost: 0.620208
Epoch 2700/100000 Cost: 0.620116
Epoch 2800/100000 Cost: 0.620026
Epoch 2900/100000 Cost: 0.619939
Epoch 3000

KeyboardInterrupt: 

In [ ]:
#데이터 평가
hypothesis = torch.sigmoid(x_train.matmul(W) + b)

prediction = hypothesis >= torch.FloatTensor([0.5])

correct_prediction = prediction.float() == y_train
print(correct_prediction[:5])

accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('The model has an accuracy of {:2.2f}% for the training set.'.format(accuracy * 100))

tensor([[True],
        [True],
        [True],
        [True],
        [True]])
The model has an accuracy of 100.00% for the training set.


In [ ]:
test_data=pd.read_csv('test.csv')
test_data

In [ ]:
x_test = torch.FloatTensor(x_train.values)
hypothesis = torch.sigmoid(x_test.matmul(W) + b)
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)