In [34]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/2022-ai-w7p1/mnist_test.csv
/kaggle/input/2022-ai-w7p1/mnist_train.csv
/kaggle/input/2022-ai-w7p1/submission.csv


In [35]:
import torch
import random

In [36]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

random.seed(777)
torch.manual_seed(777)
if device == 'cuda':
  torch.cuda.manual_seed_all(777)

In [37]:
#데이터 가져오기
import numpy as np 
import pandas as pd

#index_col=0으로 인덱스 열 제거
train_data=pd.read_csv('/kaggle/input/2022-ai-w7p1/mnist_train.csv',index_col=0)
train_data

0    1    2    3    4    5    6    7    8    9  ...  775  776  777  \
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
59996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
59997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
59998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
59999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

       778  779  780  781  782  783  784  
0      0.0  0.0  0.0  0.0  0.0  0.0  5.0  
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2      0.0  0.0  0.0  0.0  0.0  0.0  4.0  
3      0.0  0.0  0.0  0.0  0.0  0.0  1.0  
4      0.0  0.0  0.0  0.0  0.0  0.0  9.0  
...    ...  ...  ...  ...  ...  ...  ...  
59995  0.0  0.0  0.0  0.0  0.0  0.0  8.0  
59996  0.0  0.0  0.0  0.0  0.0  0.0  3.0  
59997  0.0  0.0  0.0  0.0  0.0  0.0  5.0  
59998  0.0  0.0  0.0  0.0  0.0  0.0  6.0  
59999  0.0  0.0  0.0  0.0  0.0  0.0  8.0  

[60000 rows x 785 columns]

In [38]:
x_test = pd.read_csv("/kaggle/input/2022-ai-w7p1/mnist_test.csv",index_col=0)
x_test

0    1    2    3    4    5    6    7    8    9  ...  774  775  776  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      777  778  779  780  781  782  783  
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  
9995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[10000 rows x 784 columns]

In [39]:
x_train=train_data.iloc[:,:-1]
y_train=train_data.iloc[:,-1]

x_train=torch.FloatTensor(x_train.values/255).to(device)
y_train=torch.LongTensor(y_train.values).to(device)
x_test=torch.FloatTensor(x_test.values/255).to(device)

print(x_train)
print(y_train)
print(x_test)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0')
tensor([5, 0, 4,  ..., 5, 6, 8], device='cuda:0')
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0')


In [40]:
# 학습 파라미터 설정
learning_rate = 0.001
training_epochs = 15
batch_size = 100
drop_prob = 0.3

In [41]:
#데이터 로더 설정
from torch.utils.data import DataLoader, TensorDataset

train_dataset=TensorDataset(x_train,y_train)
train_loader = DataLoader(dataset=train_dataset,batch_size=batch_size)

In [42]:
linear1 = torch.nn.Linear(784,512,bias=True)
linear2 = torch.nn.Linear(512,512,bias=True)
linear3 = torch.nn.Linear(512,512,bias=True)
linear4 = torch.nn.Linear(512,512,bias=True)
linear5 = torch.nn.Linear(512,10,bias=True)
relu = torch.nn.ReLU()
dropout = torch.nn.Dropout(p=drop_prob)

In [43]:
torch.nn.init.xavier_normal_(linear1.weight)
torch.nn.init.xavier_normal_(linear2.weight)
torch.nn.init.xavier_normal_(linear3.weight)
torch.nn.init.xavier_normal_(linear4.weight)
torch.nn.init.xavier_normal_(linear5.weight)

Parameter containing:
tensor([[-0.0180, -0.0595,  0.0064,  ..., -0.0023, -0.0860,  0.0191],
        [-0.0545,  0.0292, -0.0036,  ..., -0.0279,  0.1061, -0.0536],
        [-0.0312, -0.0075,  0.0382,  ..., -0.0651,  0.0227, -0.1196],
        ...,
        [ 0.0175,  0.0823, -0.0075,  ..., -0.0867,  0.0492,  0.0200],
        [-0.0306, -0.0145, -0.0415,  ...,  0.0258,  0.1316, -0.0382],
        [ 0.0292,  0.0643, -0.1190,  ...,  0.0634, -0.1017,  0.0353]],
       requires_grad=True)

In [44]:
#모델 선언
model = torch.nn.Sequential(linear1,relu,dropout,
                            linear2,relu,dropout,
                            linear3,relu,dropout,
                            linear4,relu,dropout,
                            linear5).to(device)

In [45]:
#손실함수와 최적화 함수 선언
loss = torch.nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate) 

In [46]:
total_batch = len(train_loader)
model.train()

for epoch in range(training_epochs):
    avg_cost = 0

    for x_train_batch, y_train_batch in train_loader:

        optimizer.zero_grad()

        x_train_batch = x_train_batch.to(device)
        y_train_batch = y_train_batch.to(device)

        hypothesis = model(x_train_batch)
        cost = loss(hypothesis, y_train_batch)
        cost.backward()
        optimizer.step()

        avg_cost += cost / total_batch

    print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))

print('Learning finished')

Epoch: 0001 cost = 0.330388010
Epoch: 0002 cost = 0.158077076
Epoch: 0003 cost = 0.120192133
Epoch: 0004 cost = 0.098268852
Epoch: 0005 cost = 0.085408390
Epoch: 0006 cost = 0.077280991
Epoch: 0007 cost = 0.071723595
Epoch: 0008 cost = 0.062449370
Epoch: 0009 cost = 0.061012615
Epoch: 0010 cost = 0.053494427
Epoch: 0011 cost = 0.052631363
Epoch: 0012 cost = 0.049961291
Epoch: 0013 cost = 0.047037393
Epoch: 0014 cost = 0.047164336
Epoch: 0015 cost = 0.046442468
Learning finished


In [47]:
# 학습된 모델로 test 데이터 예측
with torch.no_grad():
    model.eval()

    prediction = model(x_test)
    #1은 차원으로 각 행에서 가장 큰 값을 가진 인덱스를 반환한다.
    prediction=torch.argmax(prediction,1)

In [48]:
# csv 변환
prediction = prediction.cpu().numpy()
submit = pd.read_csv("/kaggle/input/2022-ai-w7p1/submission.csv")
submit['Label'] = prediction
submit.to_csv('submission.csv',index=False)